ID: v128
DETECTOR: det/det_mask_rcnn
SCORE_TH: 0.2
NUM_IDS: 903
FLAG_FILTER_SIZE: False
MODE: both
MODEL: ResNet50_AIC20_VERI_layer5_imaugclassifier_latest.pth.tar
DIST_TH: 0.000095
BLIND_OCCLUSION: False
REPROJECTION: False