ID: v172
DETECTOR: det/det_Efficient4
SCORE_TH: 0.3
NUM_IDS: 903
FLAG_FILTER_SIZE: False
MODE: both
MODEL: ResNet50_AIC20_VERI_layer5_focal classifier_best.pth.tar
DIST_TH: 0.00005
BLIND_OCCLUSION: False
REPROJECTION: False
SIZE_FC: 2048