ID: v207
DETECTOR: det/det_Efficient8
SCORE_TH: 0.3
NUM_IDS: 903
FLAG_FILTER_SIZE: False
MODE: both
MODEL: ResNet50_AIC20_VERI_layer5_CE_imaug_4096classifier_best.pth.tar
DIST_TH: 0.00005
BLIND_OCCLUSION: False
REPROJECTION: False
SIZE_FC: 4096
NMS: False
AUG_SIZE: 0.2