ID: prueba
DATASET_PATH: ./datasets/AIC19/
DETECTOR: det/det_mask_rcnn
SCORE_TH: 0.2
NUM_IDS: 903
FLAG_FILTER_SIZE: False
MODE: both
MODEL: ResNet50_AIC20_VERI_layer5_imaugclassifier_latest.pth.tar
DIST_TH: 0.00008
BLIND_OCCLUSION: True
REPROJECTION: True
SIZE_FC: 2048
NMS: False
AUG_SIZE: 0.2