ID: v218
DETECTOR: det/det_Efficient8
SCORE_TH: 0.3
NUM_IDS: 129
FLAG_FILTER_SIZE: False
MODE: both
MODEL: Imagenet
DIST_TH: 0.000095
BLIND_OCCLUSION: False
REPROJECTION: False
SIZE_FC: 2048
NMS: False
AUG_SIZE: 0.2