ID: vtiempo
DETECTOR: det/det_mask_rcnn
SCORE_TH: 0.2
NUM_IDS: 903
FLAG_FILTER_SIZE: True
MODE: both
MODEL: ResNet50_AIC20_VERI_layer5classifier_latest.pth.tar
DIST_TH: 0.00008
BLIND_OCCLUSION: True
REPROJECTION: False
SIZE_FC: 2048
NMS: True
AUG_SIZE: 0.6